# Generated by Django 4.1.5 on 2023-01-30 14:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('station_id', models.IntegerField(unique=True)),
                ('name_fi', models.CharField(default=None, max_length=50, null=True)),
                ('name_sw', models.CharField(default=None, max_length=50, null=True)),
                ('name_en', models.CharField(default=None, max_length=50, null=True)),
                ('address_fi', models.CharField(default=None, max_length=100, null=True)),
                ('address_en', models.CharField(default=None, max_length=100, null=True)),
                ('city_fi', models.CharField(default=None, max_length=50, null=True)),
                ('city_sw', models.CharField(default=None, max_length=50, null=True)),
                ('operator', models.CharField(default=None, max_length=100, null=True)),
                ('capacity', models.CharField(default=None, max_length=10, null=True)),
                ('coordinate_x', models.FloatField(default=None, null=True)),
                ('coordinate_y', models.FloatField(default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'Station',
            },
        ),
    ]
