# Generated by Django 4.1.5 on 2023-02-05 14:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartureInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField()),
                ('departure_station_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'DepartureInfo',
            },
        ),
        migrations.AddField(
            model_name='station',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 5, 14, 33, 33, 5813, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='city_fi',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='city_sw',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='operator',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ReturnInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_time', models.DateTimeField()),
                ('return_station_name', models.CharField(max_length=50)),
                ('return_station_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.station')),
            ],
            options={
                'verbose_name_plural': 'ReturnInfo',
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance', models.FloatField()),
                ('duration', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departure_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.departureinfo')),
                ('return_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.returninfo')),
            ],
            options={
                'verbose_name_plural': 'Journey',
            },
        ),
        migrations.AddField(
            model_name='departureinfo',
            name='departure_station_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.station'),
        ),
    ]
